# General
title: gaael.dev - accompagner vos transitions
description: Climat, biodiversité, intelligence collective - formations et conseil
author: Gaël Dubois

timezone: Europe/Paris
encoding: utf-8

url: https://earth.gaael.dev
baseurl: ""
